dist: trusty
sudo: required

services:
  - postgresql
addons:
  postgresql: 11.6
  apt:
    packages:
    - postgresql-11.6-postgis-2.5
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y postgresql-11.6-postgis-2.5
  - psql -c 'CREATE DATABASE spatial_db;' -U postgres
  - psql -U postgres -d spatial_db -c "CREATE EXTENSION postgis;"
  - psql -U postgres spatialdb < postgis.dump
script: psql -X -U postgres -f postgres.sql -d spatialdb

