dist: trusty
sudo: required

services:
  - postgresql
  - mongodb
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
  # Postgres/PostGIS
  - psql -c 'CREATE DATABASE spatial_db;' -U postgres
  - psql -c "CREATE EXTENSION postgis;" -U postgres -d spatial_db
  - psql -U postgres spatial_db < postgis.dump
  # MongoDB
  - mongoimport ./data/nyc_neighborhoods_wgs84.geojson -c=nyc_neighborhoods --db spatial_db
  - mongoimport ./data/nyc_homicides_wgs84.geojson -c=nyc_homicides --db spatial_db
  - mongoimport ./data/nyc_streets_wgs84.geojson -c=nyc_streets --db spatial_db
  - mongoimport ./data/nyc_subway_stations_wgs84.geojson -c=nyc_subway_stations --db spatial_db
script:
  - psql -X -U postgres -f postgres.sql -d spatial_db
  - mongo < mongo.js

