dist: trusty
sudo: required

services:
  - postgresql
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
  - psql -c 'CREATE DATABASE spatial_db;' -U postgres
  - psql -c "CREATE EXTENSION postgis;" -U postgres -d spatial_db
  - psql -U postgres spatial_db < postgis.dump
script: psql -X -U postgres -f postgres.sql -d spatial_db

